config/routes.rb
CM::Application.routes.draw do
  resources :work_memos

  resources :works

  resources :memos

  resources :musics

  post "test1_post" => "musics#test1_post"

  post "test2_post_json" => "musics#test2_post_json"
  
  post "test3_post_json" => "musics#test3_post_json"
  
  root to: "musics#index"

end

app/models/work_memo.rb
class WorkMemo < ActiveRecord::Base
  
    belongs_to :work
  
end

app/controllers/work_memos_controller.rb
class WorkMemosController < ApplicationController
  # GET /work_memos
  # GET /work_memos.json
  def index
    @work_memos = WorkMemo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @work_memos }
    end
  end

  # GET /work_memos/1
  # GET /work_memos/1.json
  def show
    @work_memo = WorkMemo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @work_memo }
    end
  end

  # GET /work_memos/new
  # GET /work_memos/new.json
  def new
    @work_memo = WorkMemo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @work_memo }
    end
  end

  # GET /work_memos/1/edit
  def edit
    @work_memo = WorkMemo.find(params[:id])
  end

  # POST /work_memos
  # POST /work_memos.json
  def create
    @work_memo = WorkMemo.new(params[:work_memo])

    respond_to do |format|
      if @work_memo.save
        format.html { redirect_to @work_memo, notice: 'Work memo was successfully created.' }
        format.json { render json: @work_memo, status: :created, location: @work_memo }
      else
        format.html { render action: "new" }
        format.json { render json: @work_memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /work_memos/1
  # PUT /work_memos/1.json
  def update
    @work_memo = WorkMemo.find(params[:id])

    respond_to do |format|
      if @work_memo.update_attributes(params[:work_memo])
        format.html { redirect_to @work_memo, notice: 'Work memo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @work_memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_memos/1
  # DELETE /work_memos/1.json
  def destroy
    @work_memo = WorkMemo.find(params[:id])
    @work_memo.destroy

    respond_to do |format|
      format.html { redirect_to work_memos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/work_memos_helper.rb
module WorkMemosHelper
end

app/views/work_memos/_form.html.erb
<%= form_for(@work_memo) do |f| %>
  <% if @work_memo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work_memo.errors.count, "error") %> prohibited this work_memo from being saved:</h2>

      <ul>
      <% @work_memo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :work_id %><br />
    <%= f.number_field :work_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/work_memos/edit.html.erb
<h1>Editing work_memo</h1>

<%= render 'form' %>

<%= link_to 'Show', @work_memo %> |
<%= link_to 'Back', work_memos_path %>

app/views/work_memos/index.html.erb
<h1>Listing work_memos</h1>

<table>
  <tr>
  	<th>Id</th>
    <th>Text</th>
    <th>Work</th>
    <th></th>
  </tr>

<% @work_memos.each do |work_memo| %>
  <tr>
  	<td><%= work_memo.id %></td>
    <td><%= link_to work_memo.text work_memo %></td>
    
    <td>
    	<% if work_memo.work_id != nil %>
    		<%= work_memo.work.serial_num %>
		<% else %>
			No data
		<% end %>
    	
	</td>

    <td><%= link_to 'Destroy', work_memo, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Work memo', new_work_memo_path %>

app/views/work_memos/new.html.erb
<h1>New work_memo</h1>

<%= render 'form' %>

<%= link_to 'Back', work_memos_path %>

app/views/work_memos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @work_memo.text %>
</p>

<p>
  <b>Work:</b>
  <%= @work_memo.work_id %>
</p>


<%= link_to 'Edit', edit_work_memo_path(@work_memo) %> |
<%= link_to 'Back', work_memos_path %>