config/routes.rb
CM::Application.routes.draw do
  resources :work_memos

  resources :works

  resources :memos

  resources :musics

  post "test1_post" => "musics#test1_post"

  post "test2_post_json" => "musics#test2_post_json"
  
  post "test3_post_json" => "musics#test3_post_json"
  
  root to: "musics#index"

end

app/models/work.rb
class Work < ActiveRecord::Base
  
    has_one :music
    has_many :work_memo
  
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  # GET /works
  # GET /works.json
  def index
    # @works = Work.all
    
    sort_format = params[:sort]
    
    if sort_format != nil
      
      @works = Work.find(:all, :order => sort_format)
      
    else
      
      @works = Work.all
      
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @works }
    end
  end

  # GET /works/1
  # GET /works/1.json
  def show
    @work = Work.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @work }
    end
  end

  # GET /works/new
  # GET /works/new.json
  def new
    @work = Work.new

    @serial_num = Work.all.size + 1

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @work }
    end
  end

  # GET /works/1/edit
  def edit
    @work = Work.find(params[:id])
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(params[:work])

    respond_to do |format|
      if @work.save
        
        music = Music.find_by_id(@work.music_id)
        
        music.update_attributes(:work_id => @work.id)
        
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render json: @work, status: :created, location: @work }
      else
        format.html { render action: "new" }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /works/1
  # PUT /works/1.json
  def update
    @work = Work.find(params[:id])

    respond_to do |format|
      if @work.update_attributes(params[:work])
        
        music = Music.find_by_id(@work.music_id)
        
        music.update_attributes(:work_id => @work.id)
        
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work = Work.find(params[:id])
    @work.destroy

    respond_to do |format|
      format.html { redirect_to works_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_form.html.erb
<%= form_for(@work) do |f| %>
  <% if @work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% @work.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	<%= f.label :title %><br />
		<%= f.text_field :title %>
    	
  </div>

  <div class="field">
    <%= f.label :serial_num %><br />

    	<% if @serial_num != nil %>
    		<%= f.text_field :serial_num, :value => @serial_num %>
		<% else %>
			<%= f.text_field :serial_num %>
		<% end %>
  </div>
  
  <div class="field">
    <%= f.label :music_id %><br />
    <%= select("work", "music_id", Music.all.collect {|m| [m.file_name, m.id]}) %>
    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/works/_item_work.html.erb
<table>
	<tr>
	  	<td><%= work.id %></td>
	  	<td><%= work.title %></td>
	</tr>
	
	<tr>
		<td>S.N.</td>
	    <td><%= link_to work.serial_num, work %></td>
	</tr>
	
	<tr>
	    <td>Mus.</td>
	    <td><%= work.music_id %>(
	    	<% if work.music != nil %>
	    		<%= work.music.file_name %>
			<% else %>
				No data
			<% end %>
	    	
	    	)</td>
	</tr>
</table>

app/views/works/_list_works.html.erb
<% @works.each do |work| %>

	<tr>
			<%= render :partial => "item_work", :locals => {:work => work} %>
	</tr>
	<%#= render :partial => 'item_work ', :locals => {:work => work} %>
	<%#= render :partial => "item_work", :locals => {:work => work} %>
<!--     <td><%#= link_to 'Destroy', work, confirm: 'Are you sure?', method: :delete %></td> -->

<% end %>

app/views/works/_list_works_header.html.erb
	<tr>
		<td>
			<%= link_to "Id", {:controller => "works", :action => "index", :sort => "id"}, 
										:class => "linked" %>
		</td>
		<td>
			<%= link_to "Title", {:controller => "works", :action => "index", :sort => "title"}, 
										:class => "linked" %>
		</td>
	</tr>  	

	<tr>
		<td colspan="2">
			<%= link_to "Serial num", {:controller => "works", :action => "index", :sort => "serial_num"}, 
										:class => "linked" %>
		</td>
	</tr>  	

	<tr>
		<td colspan="2">
			<%= link_to "Music", {:controller => "works", :action => "index", :sort => "music_id"}, 
										:class => "linked" %>
		</td>		
	</tr>  	

app/views/works/_list_works_header_original~B3.html.erb
  	<th>
  	
  		<%#= link_to "Id", {:controller => "works", :method => "index", :sort => "id"}, :class => "linked" %>
  		<%#= link_to "Id", :controller => "works", :method => "index", :sort => "id" %>
  		<%= link_to "Id", {:controller => "works", :action => "index", :sort => "id"}, :class => "linked" %>
  	
  	</th>
  	
  	<th>
  	
  		<%= link_to "Title", {:controller => "works", :action => "index", :sort => "title"}, :class => "linked" %>
  		
  	</th>
  	
    <th>
    
    	<%= link_to "Serial num", {:controller => "works", :action => "index", :sort => "serial_num"}, :class => "linked" %>
    
    </th>
    <th>
    	
    	<%= link_to "Music", {:controller => "works", :action => "index", :sort => "music_id"}, :class => "linked" %>
    	
    </th>
    <th></th>

app/views/works/edit.html.erb
<h1>Editing work</h1>

<%= render 'form' %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

app/views/works/index.html.erb
<h1>Listing works</h1>

<table>
  <tr>
<!--   	<th> -->
  		<%= render 'list_works_header' %>
<!--   	</th> -->
  </tr>

	<%#= render 'list_works' %>
	<%= render :partial => 'list_works' %>

</table>

<br />

<%= link_to 'New Work', new_work_path %>
<!-- <div class="linked">abcde</div> -->

app/views/works/new.html.erb
<h1>New work</h1>

<%= render 'form' %>

<%= link_to 'Back', works_path %>

app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Work: <%= @work.id %></b>
  
</p>


<p>
  <b>Title:</b>
  <%= @work.title %>
</p>

<p>
  <b>Serial num:</b>
  <%= @work.serial_num %>
</p>

<p>
  <b>Music:</b>
  <%= @work.music_id %>
      	(
	      	<% if @work.music != nil %>
	    		<%= @work.music.file_name %>
			<% else %>
				No data
				
			<% end %>
		)

</p>


<%= link_to 'Edit', edit_work_path(@work) %> |
<%= link_to 'Back', works_path %>