config/routes.rb
CM::Application.routes.draw do
  resources :work_memos

  resources :works

  resources :memos

  resources :musics

  post "test1_post" => "musics#test1_post"

  post "test2_post_json" => "musics#test2_post_json"
  
  post "test3_post_json" => "musics#test3_post_json"
  
  root to: "musics#index"

end

app/models/music.rb
class Music < ActiveRecord::Base
    has_many :memo
    belongs_to :work
    
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  # GET /musics
  # GET /musics.json
  def index
    @musics = Music.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @musics }
    end
  end

  # GET /musics/1
  # GET /musics/1.json
  def show
    @music = Music.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @music }
    end
  end

  # GET /musics/new
  # GET /musics/new.json
  def new
    @music = Music.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @music }
    end
  end

  # GET /musics/1/edit
  def edit
    @music = Music.find(params[:id])
  end

  # POST /musics
  # POST /musics.json
  def create
    @music = Music.new(params[:music])

    respond_to do |format|
      if @music.save
        format.html { redirect_to @music, notice: 'Music was successfully created.' }
        format.json { render json: @music, status: :created, location: @music }
      else
        format.html { render action: "new" }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /musics/1
  # PUT /musics/1.json
  def update
    @music = Music.find(params[:id])

    respond_to do |format|
      if @music.update_attributes(params[:music])
        format.html { redirect_to @music, notice: 'Music was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musics/1
  # DELETE /musics/1.json
  def destroy
    @music = Music.find(params[:id])
    @music.destroy

    respond_to do |format|
      format.html { redirect_to musics_url }
      format.json { head :no_content }
    end
  end

  def test1_post
      data = params[:test_data]
      
      @music = Music.new
      
      @music.file_name = data
      
      
      
      if data != nil and @music.save
        
        render text: data + " => OK"
        
      else
        
        render text: "Not OK"
        
      end
    
  end#def test1_post

  def test2_post_json
      data = params[:test_json][:file_name]
      
      file_path = params[:test_json][:file_path]
      
      @music = Music.new
      
      @music.file_name = data
      
      if file_path != nil
        @music.file_path = file_path
      end
      
      if data != nil and @music.save
        
        render text: data + " => OK"
        
      else
        
        render text: "Not OK"
        
      end
    
  end#def test2_post_json

  def test3_post_json
      
      data = params[:test_json]
      
      # if data != nil
      if data == nil
          render text: "No data"
          
          return
      end
      
      # Flag
      result = true
      
      # begin
          # Save data
          data.each do |item|
              file_name = item[:file_name]
              file_path = item[:file_path]
              
              @music = Music.new
              
              @music.file_name = file_name
              @music.file_path = file_path
              
              if !@music.save
                 if result == true
                    result = false
                 end 
              end
              
          end#data.each do |item|
      # rescue
#         
          # render text: "Exception!"
#           
          # return
#           
      # end#begin
      
      
      
      # Return
      if result == true
          render text: "OK"
      else
          render text: "Not OK"
      end
      
      
          # data = params[:test_json][:file_name]
#           
          # file_path = params[:test_json][:file_path]
#           
          # @music = Music.new
#           
          # @music.file_name = data
#           
          # if file_path != nil
            # @music.file_path = file_path
          # end
#           
          # if data != nil and @music.save
#             
            # render text: data + " => OK"
#             
          # else
#             
            # render text: "Not OK"
#             
          # end
    
  end#def test3_post_json

end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/musics/_form.html.erb
<%= form_for(@music) do |f| %>
  <% if @music.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@music.errors.count, "error") %> prohibited this music from being saved:</h2>

      <ul>
      <% @music.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file_name %><br />
    <%= f.text_field :file_name %>
  </div>
  <div class="field">
    <%= f.label :file_path %><br />
    <%= f.text_field :file_path %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.number_field :duration %>
  </div>

  <div class="field">
    <%= f.label :work_id %><br />
    <%= f.number_field :work_id %>
  </div>
  
  <div class="field">
    <%= f.label :date_added %><br />
    <%= f.number_field :date_added %>
  </div>
  <div class="field">
    <%= f.label :date_modified %><br />
    <%= f.number_field :date_modified %>
  </div>
  <div class="field">
    <%= f.label :file_info %><br />
    <%= f.text_area :file_info %>
  </div>
  <div class="field">
    <%= f.label :memo_self %><br />
    <%= f.text_area :memo_self %>
  </div>
  <div class="field">
    <%= f.label :located_at %><br />
    <%= f.text_field :located_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/musics/edit.html.erb
<h1>Editing music</h1>

<%= render 'form' %>

<%= link_to 'Show', @music %> |
<%= link_to 'Back', musics_path %>

app/views/musics/index.html.erb
<h1>Listing musics</h1>

<table>
  <tr>
  	<th>Num</th>
    <th>File name</th>
    <th>File path</th>
    <th>Duration</th>
    <th>Work</th>
    
    <th></th>
  </tr>

<%# @musics.each do |music| %>
<% @musics.each_with_index do |music, i| %>
  <tr>
  	<td class="col_center"><%= i + 1 %></td>
    <td><%= link_to music.file_name, music %></td>
    <td><%= music.file_path %></td>
    <td><%= music.duration %></td>
    
    <td>
    	<% if music.work_id != nil %>
    		<%= music.work_id %>
		<% else %>
			No data
		<% end %>
	</td>
    
    <td><%= link_to 'Destroy', music, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Music', new_music_path %>

<hr />
@musics.size => <%= @musics.size %>

app/views/musics/new.html.erb
<h1>New music</h1>

<%= render 'form' %>

<%= link_to 'Back', musics_path %>

app/views/musics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>File name:</b>
  <%= @music.file_name %>
</p>

<p>
  <b>File path:</b>
  <%= @music.file_path %>
</p>

<p>
  <b>Duration:</b>
  <%= @music.duration %>
</p>

<p>
  <b>Work:</b>

      	<% if @music.work_id != nil %>
    		<%= @music.work_id %>
		<% else %>
			No data
		<% end %>
  
</p>

<p>
  <b>Date added:</b>
  <%= @music.date_added %>
</p>

<p>
  <b>Date modified:</b>
  <%= @music.date_modified %>
</p>

<p>
  <b>File info:</b>
  <%= @music.file_info %>
</p>

<p>
  <b>Memo self:</b>
  <%= @music.memo_self %>
</p>

<p>
  <b>Located at:</b>
  <%= @music.located_at %>
</p>


<%= link_to 'Edit', edit_music_path(@music) %> |
<%= link_to 'Back', musics_path %>