config/routes.rb
CM::Application.routes.draw do
  resources :work_memos

  resources :works

  resources :memos

  resources :musics

  post "test1_post" => "musics#test1_post"

  post "test2_post_json" => "musics#test2_post_json"
  
  post "test3_post_json" => "musics#test3_post_json"
  
  root to: "musics#index"

end

app/models/memo.rb
class Memo < ActiveRecord::Base
  
    belongs_to :music
  
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  # GET /memos
  # GET /memos.json
  def index
    @memos = Memo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @memos }
    end
  end

  # GET /memos/1
  # GET /memos/1.json
  def show
    @memo = Memo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @memo }
    end
  end

  # GET /memos/new
  # GET /memos/new.json
  def new
    @memo = Memo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @memo }
    end
  end

  # GET /memos/1/edit
  def edit
    @memo = Memo.find(params[:id])
  end

  # POST /memos
  # POST /memos.json
  def create
    @memo = Memo.new(params[:memo])

    respond_to do |format|
      if @memo.save
        format.html { redirect_to @memo, notice: 'Memo was successfully created.' }
        format.json { render json: @memo, status: :created, location: @memo }
      else
        format.html { render action: "new" }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /memos/1
  # PUT /memos/1.json
  def update
    @memo = Memo.find(params[:id])

    respond_to do |format|
      if @memo.update_attributes(params[:memo])
        format.html { redirect_to @memo, notice: 'Memo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memos/1
  # DELETE /memos/1.json
  def destroy
    @memo = Memo.find(params[:id])
    @memo.destroy

    respond_to do |format|
      format.html { redirect_to memos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/memos/_form.html.erb
<%= form_for(@memo) do |f| %>
  <% if @memo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@memo.errors.count, "error") %> prohibited this memo from being saved:</h2>

      <ul>
      <% @memo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :music_id %><br />
    <%= f.number_field :music_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memos/edit.html.erb
<h1>Editing memo</h1>

<%= render 'form' %>

<%= link_to 'Show', @memo %> |
<%= link_to 'Back', memos_path %>

app/views/memos/index.html.erb
<h1>Listing memos</h1>

<table>
  <tr>
    <th>Text</th>
    <th>Music</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @memos.each do |memo| %>
  <tr>
    <td><%= memo.text %></td>
    <td><%= memo.music_id %></td>
    <td><%= link_to 'Show', memo %></td>
    <td><%= link_to 'Edit', edit_memo_path(memo) %></td>
    <td><%= link_to 'Destroy', memo, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Memo', new_memo_path %>

app/views/memos/new.html.erb
<h1>New memo</h1>

<%= render 'form' %>

<%= link_to 'Back', memos_path %>

app/views/memos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @memo.text %>
</p>

<p>
  <b>Music:</b>
  <%= @memo.music_id %>
</p>


<%= link_to 'Edit', edit_memo_path(@memo) %> |
<%= link_to 'Back', memos_path %>